name: C++

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libboost-dev
          # Install minimal prerequisites (Ubuntu 18.04 as reference)
          sudo apt update && sudo apt install -y cmake g++ wget unzip
          # Download and unpack sources
      - name: Install OpenCV3.X
        run: |
          wget -O opencv.zip https://github.com/opencv/opencv/archive/3.4.0.zip
          unzip opencv.zip
          wget -O opencv_contrib.zip https://github.com/opencv/opencv_contrib/archive/3.4.0.zip
          sudo apt install libopencv-dev
      - name: unzip OpenCV3.X
        run: |
          mv opencv-3.4.0 opencv
          unzip opencv_contrib.zip
          mv opencv_contrib-3.4.0 opencv_contrib
      - name: build OpenCV3.X
        run: |   
          cd opencv
          mkdir build
          cd build
          cmake -D CMAKE_BUILD_TYPE=RELEASE \
          -D CMAKE_INSTALL_PREFIX=/usr/local \
          -D INSTALL_PYTHON_EXAMPLES=OFF \
          -D INSTALL_C_EXAMPLES=OFF \
          -D OPENCV_ENABLE_NONFREE=ON \
          -D OPENCV_EXTRA_MODULES_PATH=~/opencv_contrib/modules \
          -D BUILD_EXAMPLES=OFF ..
          make
          sudo make install
          sudo ldconfig
          pkg-config –modversion opencv
      - name: Run code test suite
        run: |
          chmod +x *.cpp
          chmod +x *.out
          echo "===== Testing started ====="
          ./a.out
          echo "===== Testing finished =====" 
        
