name: C++

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libboost-dev
          # Install minimal prerequisites (Ubuntu 18.04 as reference)
          sudo apt update && sudo apt install -y cmake g++ wget unzip
          # Download and unpack sources
      - name: Install OpenCV4
        run: |
          wget -O opencv.zip https://github.com/opencv/opencv/archive/4.x.zip
          unzip opencv.zip
      - name: Run code test suite
        run: |
          chmod +x *.cpp
          echo "===== Testing started ====="
          g++ test.cpp -o test -I/opencv2/include/ -lopencv_core -lopencv_highgui -lopencv_imgcodecs -lopencv_imgproc -lopencv_videoio
          ./test
          echo "===== Testing finished =====" 
        
